---
- name: ckan_home1
  file: 
    path: /home/ubuntu/ckandeploy/lib
    state: directory

- name: Create a symbolic link 1
  become: yes
  file:
    src: /home/ubuntu/ckandeploy/lib
    dest: /usr/lib/ckan
    state: link

- name: ckan_home2
  file: 
    path: /home/ubuntu/ckandeploy/etc
    state: directory

- name: Create a symbolic link 2
  become: yes
  file:
    src: /home/ubuntu/ckandeploy/etc
    dest: /etc/ckan
    state: link

- name: Create Directory
  become: yes
  file:
    path: /usr/lib/ckan/default
    state: directory
    
- name: Create Python vENV
  command: 
    cmd: virtualenv --no-site-packages /usr/lib/ckan/default

- name: Download PIP dependencies
  pip:
    name: setuptools==20.4
    virtualenv: /usr/lib/ckan/default

- name: Download Ckan
  pip:
    name: 'git+https://github.com/ckan/ckan.git@ckan-2.7.3#egg=ckan'
    virtualenv: /usr/lib/ckan/default

- name: Dependency Ckan
  pip:
    requirements: /usr/lib/ckan/default/src/ckan/requirements.txt
    virtualenv: /usr/lib/ckan/default