---
- name: ckan_home1
  file: 
    path: $HOME/ckandeploy/lib
    state: directory
- name: Create a symbolic link 1
  become: yes
  file:
    src: $HOME/ckandeploy/lib
    dest: /usr/lib/ckan
    state: link
- name: ckan_home2
  file: 
    path: $HOME/ckandeploy/etc
    state: directory
- name: Create a symbolic link 2
become: yes
  file:
    src: $HOME/ckandeploy/etc
    dest: /etc/ckan
    state: link
     