- name: Install the Dependencies
  apt: 
    name: '{{ item }}'
    state: latest
  with_items:
  - python-dev 
  - postgresql 
  - libpq-dev
  - python-pip
  - python-virtualenv 
  - git-core 
  - solr-jetty
  - openjdk-8-jdk
  - redis-server